name: generate pacman contribution graph

on:
  schedule:
    # Run automatically every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate contribution graph SVGs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'pacman'
      
      - name: Move SVGs to output directory
        run: |
          mkdir -p output
          mv dist/pacman*.svg output/

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update pacman contribution graph"
          file_pattern: "output/pacman*.svg"
